name: 'Semantic Versioning'

author: 'Michael Wachter @mw8er'

description: 'Semantic Versioning via label of pull request and gh release, including an optional release.'

inputs:
  prefix:
    description: 'The prefix for the version number, e.g. "v" or "v."'
    required: false
    default: ''
  create_release:
    description: 'Create a release'
    required: false
    default: false
  target_branch:
    description: 'The target branch'
    required: false
    default: 'main'

outputs:
  version:
    description: "The next version number, i.e. major.minor.patch"
    value: ${{ steps.next.outputs.result }}
  version_list:
    description: "The next version list, i.e. major, major.minor, major.minor.patch"
    value: ${{ steps.next-list.outputs.result }}

runs:
  using: "composite"
  steps:
    - name: Current version
      id: current
      shell: bash
      run: |
        version=$(gh release view --json tagName --jq '.tagName' || echo "${PREFIX}0.0.0")

        echo "Current version: $version"
        echo "version=$version" >> $GITHUB_OUTPUT
      env:
        PREFIX: ${{ inputs.prefix }}
        GH_TOKEN: ${{ github.token }}
      
    - name: Next version
      id: next
      uses: actions/github-script@v7
      env:
        PREFIX: ${{ inputs.prefix }}
        VERSION: ${{ steps.current.outputs.version }}
        OWNER: ${{ github.repository_owner }}
        REPO_NAME: ${{ github.event.repository.name }}
        PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}        
      with:
        script: |
          const prefix = process.env.PREFIX;
          var version = process.env.VERSION.replace(prefix, '');
          var version_list = "";

          var version_split = version.split('.');
          var major = parseInt(version_split[0]) || 0;
          var minor = parseInt(version_split[1]) || 0;
          var patch = parseInt(version_split[2]) || 0;

          isMajor = false;
          isMinor = false;
          isPatch = false;

          var labels = context.payload.pull_request.labels;
          try {
            const pull = await github.rest.pulls.get({
              owner: process.env.OWNER,
              repo: process.env.REPO_NAME,
              pull_number: process.env.PULL_REQUEST_NUMBER
            });
            labels = pull.data.labels;
          }          
          catch(err) {
            console.log(err);
          }

          for (label of labels) {
            lowerCaseLabel = label.name.toLowerCase();
            if (lowerCaseLabel === 'major') {
              isMajor = true;
            } else if (lowerCaseLabel === 'minor') {
              isMinor = true;
            } else if (lowerCaseLabel === 'patch') {
              isPatch = true;
            }
          }

          if (isMajor) {
            major = major + 1;
            minor = 0;
            patch = 0;
          } else if (isMinor) {
            minor = minor + 1;
            patch = 0;
          } else if (isPatch) {
            patch = patch + 1;
          }

          version = prefix + major + '.' + minor + '.' + patch;
          version_list = prefix + major + ',' + prefix + major + '.' + minor + ',' + prefix + major + '.' + minor + '.' + patch;

          console.log('Next version:', version);

          return version;
        result-encoding: string

    - name: Next version list
      id: next-list
      uses: actions/github-script@v7
      env:
        VERSION: ${{ steps.next.outputs.result }}
      with:
        script: |
          var version_split = process.env.VERSION.split('.');
          var major = version_split[0];
          var minor = version_split[1];
          var patch = version_split[2];

          version_list = major + ',' + major + '.' + minor + ',' + major + '.' + minor + '.' + patch;

          console.log('Next version list:', version_list);

          return version_list;
        result-encoding: string

    - name: Create release
      if: ${{ github.event.pull_request.merged == true && inputs.create_release != 'false' && steps.next.outputs.result != steps.current.outputs.version }}
      id: create_release
      shell: bash
      run: gh release create -t "${INPUT_TITLE}" "${INPUT_TITLE}" --generate-notes --target "${TARGET_BRANCH}"
      env:
        INPUT_TITLE: ${{ steps.next.outputs.result }}
        GH_TOKEN: ${{ github.token }}
        TARGET_BRANCH: ${{ inputs.target_branch }}