on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: read

jobs:
  preview-version:
    uses: ./.github/workflows/semantic-version.yaml
    with:
      prefix: v
      create_release: false
      target_branch: main

