on:
  pull_request:
    branches:
      - main
    types:
      - closed

permissions:
  contents: write
  packages: write
  pull-requests: read

jobs:
  release-version:
    uses: ./.github/workflows/semantic-version.yaml
    with:
      prefix: v
      create_release: true
      target_branch: main
