name: 'Semantic Versioning'

on:
  workflow_call:
    inputs:
      prefix:
        description: 'The prefix for the version number, e.g. "v" or "v."'
        required: false
        type: string
      create_release:
        description: 'Create a release'
        required: false
        type: boolean
      target_branch:
        description: 'The target branch'
        required: false
        default: 'main'
        type: string

permissions:
  contents: write

jobs:
  semantic-versioning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          ref: ${{ inputs.target_branch }}

      - name: Get next version
        id: next
        uses: ./
        with:
          create_release: ${{ inputs.create_release }}
          prefix: ${{ inputs.prefix }}

        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
